-- Script para actualizar la columna gestion en la tabla dependencias
-- Ejecutar en Supabase SQL Editor

-- Gestión Académica
UPDATE dependencias SET gestion = 'academica' WHERE UPPER(nombre) IN (
  'ADMINISTRACIÓN DE EMPRESAS PREGRADO',
  'ADMINISTRACIÓN FINANCIERA POR CICLOS',
  'ÁREA DE DESARROLLO EDITORIAL',
  'ARTES PLÁSTICAS PREGRADO',
  'BIOLOGÍA PREGRADO',
  'CENTRO DE POSGRADOS',
  'CIENCIA POLÍTICA PREGRADO',
  'COMUNICACIÓN SOCIAL PREGRADO',
  'CONTADURÍA PÚBLICA PREGRADO',
  'DERECHO - SEDE POPAYÁN PREGRADO',
  'DERECHO - SEDE SANTANDER DE QUILICHAO PREGRADO',
  'DERECHO NOCTURNO - SEDE POPAYÁN PREGRADO',
  'DERECHO NOCTURNO - SEDE SANTANDER DE QUILICHAO PREGRADO',
  'DERECHO PREGRADO',
  'DIRECCIÓN DE BANDA PREGRADO',
  'DISEÑO GRÁFICO PREGRADO',
  'DIVISIÓN DE ADMISIONES, REGISTRO Y CONTROL ACADÉMICO - DARCA',
  'DIVISIÓN DE GESTIÓN DE MEDIOS Y RECURSOS BIBLIOGRÁFICOS',
  'ECONOMÍA PREGRADO',
  'ENFERMERÍA PREGRADO',
  'ESPECIALIZACIÓN EN ADMINISTRACIÓN HOSPITALARIA',
  'ESPECIALIZACIÓN EN ANATOMÍA PATOLÓGICA',
  'ESPECIALIZACIÓN EN AUDITORÍA Y GARANTÍA DE LA CALIDAD EN SALUD CON ÉNFASIS EN EPIDEMIOLOGÍA CONVENIO EAN',
  'ESPECIALIZACIÓN EN BIOÉTICA, MODALDIAD A DISTANCIA EN CONVENIO CON LA UNIVERSIDAD DEL BOSQUE',
  'ESPECIALIZACIÓN EN CIRUGÍA GENERAL',
  'ESPECIALIZACIÓN EN CONTABILIDAD PÚBLICA',
  'ESPECIALIZACIÓN EN DERECHO ADMINISTRATIVO',
  'ESPECIALIZACIÓN EN DESARROLLO DE SOLUCIONES INFORMÁTICAS',
  'ESPECIALIZACIÓN EN EDUCACIÓN COMUNITARIA',
  'ESPECIALIZACIÓN EN GERENCIA DE IMPUESTOS',
  'ESPECIALIZACIÓN EN GERENCIA DE PROYECTOS',
  'ESPECIALIZACIÓN EN GERENCIA DE PROYECTOS CONVENIO UNINARIÑO',
  'ESPECIALIZACIÓN EN GINECOLOGÍA Y OBSTETRICIA',
  'ESPECIALIZACIÓN EN INGENIERÍA DE LA CONSTRUCCIÓN',
  'ESPECIALIZACIÓN EN INGENIERÍA DE VÍAS TERRESTRES',
  'ESPECIALIZACIÓN EN INTERVENCIÓN DEL LENGUAJE INFANTIL',
  'ESPECIALIZACIÓN EN MEDICINA FAMILIAR',
  'ESPECIALIZACIÓN EN MEDICINA INTERNA',
  'ESPECIALIZACIÓN EN MERCADEO CORPORATIVO',
  'ESPECIALIZACIÓN EN NEUROREHABILITACIÓN',
  'ESPECIALIZACIÓN EN PAVIMENTOS',
  'ESPECIALIZACIÓN EN PEDIATRÍA',
  'ESPECIALIZACIÓN EN REDES Y SERVICIOS TELEMÁTICOS',
  'ESPECIALIZACIÓN EN REVISORIA FISCAL Y AUDITORÍA INTERNACIONAL',
  'ESPECIALIZACIÓN EN SEGURIDAD Y SALUD EN EL TRABAJO',
  'ESPECIALIZACIÓN EN SISTEMAS DE RADIOCOMUNICACIONES',
  'ESPECIALIZACIÓN EN SISTEMAS INTEGRADOS DE LA CALIDAD',
  'ESPECIALIZACIÓN EN TELEMÁTICA',
  'ESPECIALIZACIÓN EN TRÁNSITO',
  'FACULTAD DE ARTES',
  'FACULTAD DE CIENCIAS AGRARIAS',
  'FACULTAD DE CIENCIAS CONTABLES, ECONÓMICAS Y ADMINISTRATIVAS',
  'FACULTAD DE CIENCIAS DE LA SALUD',
  'FACULTAD DE CIENCIAS HUMANAS Y SOCIALES',
  'FACULTAD DE CIENCIAS NATURALES, EXACTAS Y DE LA EDUCACIÓN',
  'FACULTAD DE DERECHO, CIENCIAS POLÍTICAS Y SOCIALES',
  'FACULTAD DE INGENIERÍA CIVIL',
  'FACULTAD DE INGENIERÍA ELECTRÓNICA Y TELECOMUNICACIONES',
  'FILOSOFÍA PREGRADO',
  'FISIOTERAPIA PREGRADO',
  'FONOAUDIOLOGÍA PREGRADO',
  'GEOGRAFÍA DEL DESARROLLO REGIONAL Y AMBIENTAL PREGRADO',
  'GEOTECNOLOGÍA',
  'GESTIÓN ACADÉMICA',
  'HISTORIA PREGRADO',
  'INGENIERÍA AGROINDUSTRIAL PREGRADO',
  'INGENIERÍA AGROPECUARIA PREGRADO',
  'INGENIERÍA AMBIENTAL PREGRADO',
  'INGENIERÍA CIVIL PREGRADO',
  'INGENIERÍA DE SISTEMAS PREGRADO',
  'INGENIERÍA ELECTRÓNICA Y DE TELECOMUNICACIONES PREGRADO',
  'INGENIERÍA EN AUTOMÁTICA INDUSTRIAL PREGRADO',
  'INGENIERÍA FÍSICA PREGRADO',
  'INGENIERÍA FORESTAL PREGRADO',
  'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN CIENCIAS NATURALES Y EDUCACIÓN AMBIENTAL PREGRADO',
  'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN EDUCACIÓN ARTÍSTICA PREGRADO',
  'LICENCIATURA EN EDUCACIÓN BÁSICA CON ÉNFASIS EN LENGUA CASTELLANA E INGLÉS PREGRADO',
  'LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA PREGRADO',
  'LICENCIATURA EN EDUCACIÓN FÍSICA, RECREACIÓN Y DEPORTES PREGRADO',
  'LICENCIATURA EN ETNOEDUCACIÓN PREGRADO',
  'LICENCIATURA EN LENGUAS MODERNAS CON ÉNFASIS EN INGLÉS Y FRANCÉS - SEDE POPAYÁN PREGRADO',
  'LICENCIATURA EN LENGUAS MODERNAS CON ÉNFASIS EN INGLÉS Y FRANCÉS - SEDE SANTANDER PREGRADO',
  'LICENCIATURA EN LITERATURA Y LENGUA CASTELLANA PREGRADO',
  'LICENCIATURA EN MATEMÁTICAS PREGRADO',
  'LICENCIATURA EN MÚSICA PREGRADO',
  'MAESTRÍA EN ADMINISTRACIÓN DE EMPRESAS DE SALUD - MBA_EN_SALUD',
  'MAESTRÍA EN ANTROPOLOGÍA',
  'MAESTRÍA EN ARTES INTEGRADAS CON EL AMBIENTE',
  'MAESTRÍA EN CIENCIAS AGRARIAS',
  'MAESTRÍA EN CIENCIAS HUMANAS',
  'MAESTRÍA EN CIENCIAS MATEMÁTICAS',
  'MAESTRÍA EN CIENCIAS QUÍMICAS',
  'MAESTRÍA EN COMPUTACIÓN',
  'MAESTRÍA EN CONTABILIDAD Y FINANZAS',
  'MAESTRÍA EN COOPERACIÓN INTERNACIONAL CONVENIO NORTE SUR - UNIVERSIDAD DEL CAUCA',
  'MAESTRÍA EN EDUCACIÓN',
  'MAESTRÍA EN EDUCACIÓN POPULAR',
  'MAESTRÍA EN ESTUDIOS DE RIESGOS DE DESASTRE Y ORDENAMIENTO TERRITORIAL',
  'MAESTRÍA EN ESTUDIOS INTERCULTURALES',
  'MAESTRÍA EN ESTUDIOS MULTIDISCIPLINARIOS DEL DESARROLLO',
  'MAESTRÍA EN ÉTICA Y FILOSOFÍA POLÍTICA',
  'MAESTRÍA EN GESTIÓN DE ORGANIZACIONES Y PROYÉCTOS',
  'MAESTRÍA EN GOBIERNO',
  'MAESTRÍA EN HISTORIA',
  'MAESTRÍA EN INGENIERÍA - ÁREA ELECTRÓNICA Y TELECOMUNICACIONES',
  'MAESTRÍA EN INGENIERÍA FÍSICA',
  'MAESTRÍA EN INGENIERÍA TELEMÁTICA',
  'MAESTRÍA EN MÚSICA',
  'MAESTRÍA EN RECURSOS HIDROBIOLÓGICAS CONTINENTALES',
  'MAESTRÍA EN REVITALIZACIÓN Y ENSEÑANZA DE LENGUAS INDÍGENAS',
  'MATEMÁTICAS PREGRADO',
  'MEDICINA PREGRADO',
  'MÚSICA INSTRUMENTAL PREGRADO',
  'PROGRAMA DE PERMANENCIA Y GRADUACIÓN',
  'QUÍMICA PREGRADO',
  'TECNOLOGÍA EN TELEMÁTICA',
  'TURISMO PREGRADO'
);

-- Gestión Estratégica
UPDATE dependencias SET gestion = 'estrategica' WHERE UPPER(nombre) IN (
  'ÁREA DE EGRESADOS',
  'ÁREA DE INTERACCIÓN SOCIAL',
  'CENTRO DE GESTIÓN DE LAS COMUNICACIONES',
  'DIVISIÓN DE INNOVACIÓN, EMPRENDIMIENTO Y ARTICULACIÓN CON EL ENTORNO - DAE',
  'OFICINA DE PLANEACIÓN Y DESARROLLO INSTITUCIONAL',
  'OFICINA DE RELACIONES INTERINSTITUCIONALES E INTERNACIONALES - ORI'
);

-- Gestión Administrativa
UPDATE dependencias SET gestion = 'administrativa' WHERE UPPER(nombre) IN (
  'ÁREA DE ADQUISICIONES E INVENTARIOS',
  'ÁREA DE GESTIÓN DOCUMENTAL',
  'DIVISIÓN DE GESTIÓN DEL TALENTO HUMANO',
  'DIVISIÓN DE GESTIÓN FINANCIERA',
  'DIVISIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES - TICs',
  'GESTIÓN ADMINISTRATIVA',
  'GESTIÓN DE BIENES Y SERVICIOS',
  'GESTIÓN DEL MANTENIMIENTO DE BIENES MUEBLES, INMUEBLES Y EQUIPOS',
  'OFICINA JURÍDICA',
  'SECRETARIA GENERAL'
);

-- Gestión de Cultura y Bienestar
UPDATE dependencias SET gestion = 'cultura' WHERE UPPER(nombre) IN (
  'DIVISIÓN DE GESTIÓN DE LA CULTURA',
  'DIVISIÓN DE GESTIÓN DE LA RECREACIÓN Y EL DEPORTE',
  'DIVISIÓN DE GESTIÓN DE SALUD INTEGRAL Y DESARROLLO HUMANO',
  'UNIDAD DE SALUD',
  'VICERRECTORÍA DE CULTURA Y BIENESTAR'
);

-- Gestión de Control
UPDATE dependencias SET gestion = 'control' WHERE UPPER(nombre) IN (
  'ÁREA DE SEGURIDAD, CONTROL Y MOVILIDAD',
  'CENTRO DE GESTIÓN DE LA CALIDAD Y LA ACREDITACION INSTITUCIONAL',
  'OFICINA DE CONTROL INTERNO - OCI'
);

-- Gestión de la Investigación
UPDATE dependencias SET gestion = 'investigacion' WHERE UPPER(nombre) IN (
  'DOCTORADO EN ANTROPOLOGÍA',
  'DOCTORADO EN CIENCIAS - QUIMICA',
  'DOCTORADO EN CIENCIAS AGRARIAS Y AGROINDUSTRIALES',
  'DOCTORADO EN CIENCIAS DE LA EDUCACIÓN',
  'DOCTORADO EN CIENCIAS DE LA ELECTRÓNICA',
  'DOCTORADO EN CIENCIAS HUMANAS',
  'DOCTORADO EN CIENCIAS MATEMÁTICAS',
  'DOCTORADO EN ETNOBIOLOGÍA Y ESTUDIOS BIOCULTURALES',
  'DOCTORADO EN INGENIERÍA TELEMÁTICA',
  'GESTIÓN DE LA INVESTIGACIÓN'
);

-- Verificar actualizaciones
SELECT gestion, COUNT(*) as total
FROM dependencias
GROUP BY gestion
ORDER BY gestion;
